m3uPath: ../sample/sample.m3u
httpPort: "80"
httpsPort: "443"
cerPath: ../sample/certs/redbulltv.cer
pemPath: ../sample/certs/redbulltv.pem
keyPath: ../sample/certs/redbulltv.key
logToFile: true
loggingPath: log
recents: []
favorites: []
